### ISSUE TITLE
Error opening audio: Internal PortAudio error

### ISSUE THREAD

**Issue by chatOpastel** [pd-l2ork/pd-l2ork#12]
Hey there, I don't know if the purpose of this issue fits the git repo, but I don't know exactly where to post it.

I reached to an issue this morning :

Just as the title mentionned it, the PortAudio is reaching an error. It happens everytime I turn I/O the DSP and change parameters in the audio preferences. I tried to search for answers on forums like pdpatchrepo.com, people had the same issue but nothing worked for me... 
It seems to be linked with externals VST I installed (Vital and Leveling Tool) and with the vstplugin~ object. 
Everything works fine on the pd eventoop app, but not in pd-l2ork...  

What do you suggest I should try ? Is there something I don't see ?

I'm runing pd in a Ventura 13.0.1 macOS.

Best regards

**Comment by pd-l2ork** [comment]
Since it appears VST plugins and/or PortAudio are the culprit, this is likely an upstream question for PortAudio and/or developers of those plugins. I do seem to recall PortAudio having some issues on newer OSX versions, but that may have been fixed since. Hope this helps. Also, what do you mean by "pd eventloop app"? Lastly, are you using natively compiled vstplugin~ for pd-l2ork or are you using Deken version? I encourage running only native compiled objects.

**Comment by pd-l2ork** [comment]
Glad to hear it works. Thanks for your feedback.
